name: OpenSSH Vulnerability Scan

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          repository: drongrifon/openssh-portable  #karpov
          fetch-depth: 0

      - name: Run Trivy scan
        uses: aquasecurity/trivy-action@0.9.1
        with:
          scan-type: 'fs'
          scan-ref: '.'
          severity: 'HIGH,CRITICAL'
          exit-code: '1'
          security-checks: 'vuln'
          format: 'table'
