name: Simple OpenSSH Trivy Scan

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  scan:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          repository: drongrifon/openssh-portable
          path: openssh

      - name: Run Trivy scan
        uses: aquasecurity/trivy-action@0.14.0
        with:
          scan-type: 'fs'
          scan-ref: 'openssh'
          severity: 'HIGH,CRITICAL'
          exit-code: '1'
          format: 'table'
          ignore-unfixed: true
